---
title: "Eureka Project"
author: "Jinseob Kim"
date: "February, 2018"
csl: /home/secondmath/Dropbox/myarticle/bibtex_style/plos.csl
output:
  html_document:
    code_folding: show
    fig_height: 6
    fig_width: 9
    highlight: textmate
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
  pdf_document:
    fig_height: 6
    fig_width: 9
  word_document:
    fig_height: 6
    fig_width: 9
    toc: yes
header-includes: \usepackage{kotex} \usepackage[doublespacing]{setspace}  \usepackage{multirow}
subtitle: "Decentralize Academic Publishing"
bibliography: [references.bib, refarxiv.bib]
editor_options: 
  chunk_output_type: console
---

<style>
   p {line-height: 2.5em;}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,fig.align="center",message=FALSE, warning=FALSE,fig.height = 7,cache=T,dpi=300)
library(knitr);library(knitcitations);library(data.table)
cleanbib()
options("citation_format" = "pandoc")
```

```{r,echo=FALSE}
setwd("/home/secondmath/Dropbox/ethereum/Eureka/whitepaper")
write("","references.bib")
```




## Background

## Problem

## Solution

## Plan 

## Member

랄라라 간다`r citep(c("10.1038/nature24671","10.1016/j.ajhg.2018.01.014"))`. 간다[`r citet("10.1038/nature25744")`;@He_2018]. 가자[@He_2018;`r citet("10.1038/nature24671")`].

arxiv도 같이 간다[@arxiv1403.2036;`r citet("10.1038/nature24671")`;`r citet("10.1038/nature24671")`].

```{r,echo=F}
write.bibtex(file="references.bib")
```
## References


